apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: nginx-servc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30008
  selector:
    app: frontend
    
