apiVersion: v1
kind: Pod
metadata:
  name: random-number
spec:
  - image: alpine
    name: alpine
    command: ["/bin/sh","-c"]
    args: ["shuf -i 0-120 -n 1 >> /opt/number.out"]
    volumeMounts:
    - mountPath: /opt
      name: dataVolume
  volume:
  - name: dataVolume
    hostPath:
      path: /data
      type: Directory